version: '3.4'

services:
  server:
    image: dockerme-server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    image: dockerme-client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "7001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
